import pino from "pino";
import { createAccount } from "genlayer-js";
import { createLiveAdapter } from "@faultpact/contract";
import { createDb } from "@faultpact/db";
import { reporterPreflight } from "@faultpact/monitoring";
import { loadEnv } from "@faultpact/shared";
import { FaultPactIndexer } from "./indexer.js";
import { MonitoringWorker } from "./monitor.js";

const env = loadEnv();
if (env.AUTO_ONCHAIN_SUBMISSION) throw new Error("AUTO_ONCHAIN_SUBMISSION is fail-closed: a signer transport must be explicitly implemented and verified before enabling it");
const logger = pino({ level: env.LOG_LEVEL, base: { service: "faultpact-worker", region: env.PROBE_REGION, mode: env.MONITOR_MODE } });
const db = createDb(env.DATABASE_URL);
const contract = await createLiveAdapter();
const reporterAccount = env.REPORTER_PRIVATE_KEY ? createAccount(env.REPORTER_PRIVATE_KEY as `0x${string}`) : undefined;
const reporterStatus = await reporterPreflight({ hasPrivateKey: reporterAccount !== undefined, ...(reporterAccount ? { reporterAddress: reporterAccount.address } : {}), isAuthorized: (address) => contract.isAuthorizedReporter(address) });
const indexer = new FaultPactIndexer(db, contract, { logger });
const monitor = new MonitoringWorker(db, { region: env.PROBE_REGION, mode: env.MONITOR_MODE, timeoutMs: env.PROBE_TIMEOUT_MS, maxResponseBytes: env.PROBE_MAX_RESPONSE_BYTES, evidenceMaxBytes: env.EVIDENCE_MAX_BYTES, rawRetentionSeconds: env.PROBE_RAW_RETENTION_SECONDS, evidencePublicBaseUrl: env.EVIDENCE_PUBLIC_BASE_URL, reporterMode: reporterStatus.mode, ...(env.PROBE_REFERENCE_RPC_URL ? { referenceUrl: env.PROBE_REFERENCE_RPC_URL } : {}), logger });
const controller = new AbortController();
process.once("SIGINT", () => controller.abort());
process.once("SIGTERM", () => controller.abort());
logger.info({ chainId: contract.chainId, address: contract.address }, "worker starting");
logger.info({ reporterMode: reporterStatus.mode, reason: reporterStatus.reason }, "reporter preflight complete");
await Promise.all([indexer.run(env.INDEXER_POLL_INTERVAL_MS, env.INDEXER_RECONCILE_INTERVAL_MS, controller.signal), monitor.run(env.PROBE_INTERVAL_MS, controller.signal)]);
await db.$disconnect();
