import Link from "next/link";
import { Shell } from "../components/shell";
import { LandingStats } from "../components/explorer";
import { ProductGlyph } from "../components/ui";

const pipeline = ["Bonded SLA", "Live probes", "Evidence lock", "Canonical facts", "Claim settlement"];

export default function HomePage() {
  return <Shell><main className="landing-main">
    <section className="hero-section"><div className="hero-copy"><p className="eyebrow"><span className="eyebrow-line" />Bonded service commitments</p><h1>Reliability with <em>consequences.</em></h1><p className="hero-lede">Providers lock capital behind SLA terms called Pacts. Customers buy Coverage. If a service fails, evidence informs facts that GenLayer resolves; the contract applies the Pact and pays eligible Claims from Provider backing.</p><div className="hero-actions"><Link className="button button-coral" href="/explore">Explore Pacts <span>↗</span></Link><Link className="button button-outline" href="/docs">Read the docs <span>→</span></Link></div><div className="hero-note"><span className="status-dot" />GenLayer Studio Development Preview <span className="mono">61997</span></div></div>
      <div className="hero-system" aria-label="FaultPact turns a service commitment into a settled claim"><div className="system-top"><span className="mono">FAULTPACT / PACT LIFECYCLE</span><span>CHAIN 61997</span></div><ol className="lifecycle-steps"><li><span>01</span><div><strong>Provider bonds capital</strong><small>Backing for published SLA terms</small></div></li><li><span>02</span><div><strong>Service is monitored</strong><small>Probe signals identify a possible incident</small></div></li><li><span>03</span><div><strong>Evidence is checked</strong><small>Provenance and hashes travel with the record</small></div></li><li><span>04</span><div><strong>GenLayer resolves facts</strong><small>Canonical facts describe what happened</small></div></li><li><span>05</span><div><strong>Contract evaluates the Pact</strong><small>Eligible claims settle from Provider backing</small></div></li></ol><div className="system-foot"><span><i className="tiny-dot lime" />Facts resolved</span><span><i className="tiny-dot coral" />Payout by frozen terms</span></div></div>
    </section>
    <section className="pipeline-section"><div className="section-intro"><p className="eyebrow">The protocol loop</p><h2>A promise that leaves a trail.</h2><p>Every step moves from an observable signal to an auditable financial result. The model resolves incident facts; frozen Pact terms decide what those facts mean.</p></div><div className="pipeline">{pipeline.map((item, index) => <div className="pipeline-item" key={item}><span className="pipeline-index">0{index + 1}</span><strong>{item}</strong>{index < pipeline.length - 1 ? <span className="pipeline-arrow">→</span> : null}</div>)}</div></section>
    <section className="split-section"><div className="section-intro"><p className="eyebrow">Built around the hard part</p><h2>Evidence first. Money last.</h2><p>FaultPact keeps observation, resolution, Pact evaluation, and settlement distinct. That separation makes the protocol legible when a service is under pressure.</p><Link className="text-link" href="/docs/evidence">Understand the evidence model →</Link></div><div className="ledger-visual"><div className="ledger-row ledger-header"><span>input</span><span>trust</span><span>result</span></div><div className="ledger-row"><ProductGlyph kind="service" size={22} /><span>probe window</span><b className="tag-neutral">observed</b></div><div className="ledger-row"><ProductGlyph kind="evidence" size={22} /><span>reporter evidence</span><b className="tag-lime">hash locked</b></div><div className="ledger-row"><ProductGlyph kind="resolution" size={22} /><span>canonical facts</span><b className="tag-lime">finalized</b></div><div className="ledger-row"><ProductGlyph kind="settlement" size={22} /><span>Pact evaluation</span><b className="tag-coral">mechanical</b></div></div></section>
    <section className="audience-section"><div className="audience-card audience-provider"><p className="eyebrow">For Providers</p><h2>Inspect the capital behind a promise.</h2><p>Review published Pact terms, Provider backing, and reserve state. Provider write actions are not available in this console.</p><Link className="text-link" href="/providers">Browse Providers →</Link><div className="audience-mark"><ProductGlyph kind="bond" size={64} /></div></div><div className="audience-card audience-customer"><p className="eyebrow">For Customers</p><h2>Buy protection you can actually read.</h2><p>Compare SLA clauses, Coverage limits, evidence provenance, and claim deadlines before your wallet signs.</p><Link className="text-link" href="/pacts">Browse Pacts →</Link><div className="audience-mark"><ProductGlyph kind="coverage" size={64} /></div></div></section>
    <section className="protocol-section"><div><p className="eyebrow">The live protocol</p><h2>Not a simulation.</h2><p>Browse the indexed Studio Dev deployment. When a record is missing, FaultPact says so instead of filling the gap with made-up activity.</p></div><LandingStats /></section>
    <section className="final-cta"><p className="eyebrow">Make reliability legible</p><h2>Start with the facts.</h2><div><Link className="button button-dark" href="/explore">Open explorer ↗</Link><Link className="button button-outline" href="/docs/getting-started">Get started →</Link></div></section>
  </main></Shell>;
}
