import Link from "next/link";
import { Shell } from "../components/shell";
import { LandingStats } from "../components/explorer";
import { ProductGlyph } from "../components/ui";

const pipeline = ["Bonded SLA", "Live probes", "Evidence lock", "Canonical facts", "Claim settlement"];

export default function HomePage() {
  return <Shell><main className="landing-main">
    <section className="hero-section"><div className="hero-copy"><p className="eyebrow"><span className="eyebrow-line" />A reliability exchange for real infrastructure</p><h1>Reliability with <em>consequences.</em></h1><p className="hero-lede">Providers bond capital behind measurable service commitments. Customers buy Coverage that can settle when the facts say a promise was missed.</p><div className="hero-actions"><Link className="button button-coral" href="/explore">Explore the protocol <span>↗</span></Link><Link className="button button-outline" href="/docs">Read the docs <span>→</span></Link></div><div className="hero-note"><span className="status-dot" />Frozen on GenLayer Studio Dev <span className="mono">61997</span></div></div>
      <div className="hero-system" aria-label="FaultPact reliability system sequence"><div className="system-top"><span className="mono">FAULTPACT / LIVE SYSTEM</span><span className="system-pulse"><i />signal path active</span></div><div className="system-stage"><div className="orbit orbit-a" /><div className="orbit orbit-b" /><div className="system-core"><span className="core-label">PACT</span><strong>99.95</strong><small>availability floor</small></div><div className="system-node node-one"><span>us-east</span><b>42 ms</b></div><div className="system-node node-two"><span>evidence</span><b>sha locked</b></div><div className="system-node node-three"><span>facts</span><b>2 / 2</b></div><div className="trace trace-one" /><div className="trace trace-two" /><div className="trace trace-three" /></div><div className="system-foot"><span><i className="tiny-dot lime" />canonical facts</span><span><i className="tiny-dot coral" />deterministic claim</span></div></div>
    </section>
    <section className="pipeline-section"><div className="section-intro"><p className="eyebrow">The protocol loop</p><h2>A promise that leaves a trail.</h2><p>Every step moves from an observable signal to an auditable financial result. The model resolves incident facts; frozen Pact terms decide what those facts mean.</p></div><div className="pipeline">{pipeline.map((item, index) => <div className="pipeline-item" key={item}><span className="pipeline-index">0{index + 1}</span><strong>{item}</strong>{index < pipeline.length - 1 ? <span className="pipeline-arrow">→</span> : null}</div>)}</div></section>
    <section className="split-section"><div className="section-intro"><p className="eyebrow">Built around the hard part</p><h2>Evidence first. Money last.</h2><p>FaultPact keeps observation, resolution, Pact evaluation, and settlement distinct. That separation makes the protocol legible when a service is under pressure.</p><Link className="text-link" href="/docs/evidence">Understand the evidence model →</Link></div><div className="ledger-visual"><div className="ledger-row ledger-header"><span>input</span><span>trust</span><span>result</span></div><div className="ledger-row"><ProductGlyph kind="service" size={22} /><span>probe window</span><b className="tag-neutral">observed</b></div><div className="ledger-row"><ProductGlyph kind="evidence" size={22} /><span>reporter evidence</span><b className="tag-lime">hash locked</b></div><div className="ledger-row"><ProductGlyph kind="resolution" size={22} /><span>canonical facts</span><b className="tag-lime">finalized</b></div><div className="ledger-row"><ProductGlyph kind="settlement" size={22} /><span>Pact evaluation</span><b className="tag-coral">mechanical</b></div></div></section>
    <section className="audience-section"><div className="audience-card audience-provider"><p className="eyebrow">For Providers</p><h2>Put capital behind a promise you can operate.</h2><p>Create a Service, publish immutable Pact terms, and see exactly what is allocated, reserved, and free.</p><Link className="text-link" href="/provider">Open provider console →</Link><div className="audience-mark"><ProductGlyph kind="bond" size={64} /></div></div><div className="audience-card audience-customer"><p className="eyebrow">For Customers</p><h2>Buy protection you can actually read.</h2><p>Compare SLA clauses, Coverage limits, evidence provenance, and claim deadlines before your wallet signs.</p><Link className="text-link" href="/pacts">Browse Pacts →</Link><div className="audience-mark"><ProductGlyph kind="coverage" size={64} /></div></div></section>
    <section className="protocol-section"><div><p className="eyebrow">The live protocol</p><h2>Not a simulation.</h2><p>Browse the indexed Studio Dev deployment. When a record is missing, FaultPact says so instead of filling the gap with made-up activity.</p></div><LandingStats /></section>
    <section className="final-cta"><p className="eyebrow">Make reliability legible</p><h2>Start with the facts.</h2><div><Link className="button button-dark" href="/explore">Open explorer ↗</Link><Link className="button button-outline" href="/docs/getting-started">Get started →</Link></div></section>
  </main></Shell>;
}
