import Link from "next/link";
import type { ReactNode } from "react";

export const docs: Record<string, { title: string; kicker: string; description: string; body: ReactNode }> = {
  "getting-started": { title: "Start with the exchange", kicker: "Getting started", description: "A short route through the Provider, Customer, and integration workflows.", body: <><h2>Three actors, one source of truth</h2><p>Providers create Services and bond capital behind published Pact terms. Customers purchase Coverage against those terms. Monitoring produces signals and reporter evidence; the frozen contract resolves the financial state.</p><div className="doc-callout"><strong>Browsing never requires a wallet.</strong><span>Connect only when you are ready to sign a user action on Chain 61997.</span></div><h2>Choose a path</h2><div className="doc-paths"><Link href="/docs/providers">I am a Provider <span>→</span></Link><Link href="/docs/customers">I am a Customer <span>→</span></Link><Link href="/docs/api">I am integrating FaultPact <span>→</span></Link></div></> },
  providers: { title: "Provider guide", kicker: "Providers", description: "Understand Provider registration, Pact terms, capital, and reserve constraints.", body: <><h2>Publish what you can operate</h2><p>A Pact is a set of frozen SLA terms for a Service. Published terms are not edited in place. If the commitment changes, create a revision and review it as a new object.</p><h2>Capital vocabulary</h2><ul><li><strong>Total</strong> is the vault balance.</li><li><strong>Allocated</strong> is capital assigned to Pacts.</li><li><strong>Reserved</strong> backs active Coverage and pending claims.</li><li><strong>Free</strong> is the remaining amount available for an eligible operation.</li></ul><p>Reserved capital is unavailable for withdrawal while Coverage or Claims need it. The current Provider console is read-only: registration, Service creation, Pact publishing, and capital transactions are not exposed in the web interface.</p></> },
  "providers/services": { title: "Services", kicker: "Providers", description: "A Service is the thing the Pact promises to keep reliable.", body: <><h2>Keep identity separate from performance</h2><p>Service metadata describes what is being monitored. Monitoring signals are operational context; the contract’s canonical Incident facts remain the basis for claim evaluation.</p><h2>Scope is explicit</h2><p>Use a normalized region such as <code>us-east</code>, or the explicit global token. Empty scope is not a wildcard.</p></> },
  "providers/pacts": { title: "Pacts", kicker: "Providers", description: "Readable terms for an immutable commitment.", body: <><h2>Terms customers can compare</h2><p>Availability, p95 latency, error rate, block lag, duration, scope, Coverage bounds, premium, and claim window are all material. A product surface should translate protocol units without losing the raw values.</p><div className="code-block"><code>availability_ppm = 999500</code><code>p95_latency_ms = 150</code><code>scope = &quot;us-east&quot;</code></div></> },
  "providers/capital": { title: "Capital", kicker: "Providers", description: "Why allocation and reserve are different balances.", body: <><h2>Withdrawal is a lifecycle</h2><p>Capital that is reserved cannot be withdrawn immediately. A request enters the contract’s cooldown path; execution is separate. The app should show request, unlock time, and execute as distinct states.</p><p>FaultPact never server-signs provider capital operations.</p></> },
  customers: { title: "Customer guide", kicker: "Customers", description: "Read the protection before your wallet signs.", body: <><h2>Coverage is a bounded promise</h2><p>Coverage points to a Pact. The Pact defines the service scope, duration, thresholds, premium, deductible, and payout cap. Capacity is a live protocol constraint, not a UI estimate.</p><h2>File while the window is open</h2><p>Claims may need to be filed before Incident resolution so the reserve remains locked. Always check the onchain deadline shown for the Coverage.</p></> },
  "customers/coverage": { title: "Coverage", kicker: "Customers", description: "What the purchase protects and what it does not.", body: <><h2>Review before buying</h2><p>Review the Service, Provider, Pact revision, scope, Coverage amount, premium, maximum payout, start/end, minimum incident duration, and claim deadline. The contract is authoritative if the index is behind.</p></> },
  "customers/incidents": { title: "Incidents", kicker: "Customers", description: "Follow one incident from evidence to final facts.", body: <><h2>One Incident, one canonical fact set</h2><p>Evidence can be authoritative or supplemental. Authoritative evidence must be tied to an authorized reporter and structured schema. Hash validity verifies bytes; it does not prove truth on its own.</p><p>GenLayer resolves Incident facts. Pact-specific evaluation is deterministic and happens afterward.</p></> },
  "customers/claims": { title: "Claims", kicker: "Customers", description: "A claim is evaluated against facts, not a free-form explanation.", body: <><h2>What happens next</h2><ol><li>File the claim before the Coverage deadline.</li><li>Wait for the Incident’s resolution lifecycle.</li><li>Review the matched clause and final stored result.</li><li>Settlement creates internal FaultPact credit when eligible.</li></ol><div className="doc-callout warning"><strong>Claim filing is not exposed in the current web interface.</strong><span>The customer pages show indexed Coverage, Incident, and Claim state. The contract remains the authority for owner, deadline, overlap, and duplicate checks.</span></div></> },
  monitoring: { title: "Monitoring", kicker: "Operations", description: "Operational telemetry that does not pretend to be settlement truth.", body: <><h2>Signals have a job</h2><p>Regional workers probe trusted RPC targets, validate JSON-RPC responses, aggregate windows, and apply persistence before creating candidates. A single timeout does not become a financial fact.</p><div className="doc-callout warning"><strong>UNKNOWN is not HEALTHY.</strong><span>A stale worker, missing reference head, or unavailable target is shown as unknown or unavailable.</span></div></> },
  evidence: { title: "Evidence", kicker: "Security model", description: "Exact bytes, explicit provenance, deterministic support.", body: <><h2>Two dimensions of trust</h2><p>Authoritative evidence is submitted by an authorized reporter and passes the structured schema. Supplemental evidence can add context, but cannot establish payout-bearing facts by itself.</p><h2>Hash display</h2><p>SHA-256 proves the fetched bytes match the committed hash. It does not prove who produced a measurement or whether a measurement is true. Reporter identity and quorum are separate controls.</p><h2>Immutable artifacts</h2><p>Canonical JSON is stored as exact bytes behind a content-addressed URL. Fetching the raw artifact and hashing it should reproduce the recorded SHA-256.</p></> },
  resolution: { title: "Resolution", kicker: "GenLayer facts", description: "Canonical Incident facts stay separate from Pact evaluation.", body: <><h2>Facts once, evaluations many</h2><p>The same finalized Incident facts can be reused by multiple Pacts. One Pact can match p95 300 ms against a 150 ms threshold while another does not match against 500 ms.</p><p>The model does not choose payout amount, reserve accounting, or arbitrary slashing.</p></> },
  challenges: { title: "Challenges", kicker: "Independent review", description: "A challenge opens another evidence path under the same trust model.", body: <><h2>Challenge does not equal reversal</h2><p>A challenger posts the required bond and submits evidence within the protocol window. The contract applies the same provenance and support requirements. A challenge can change facts only through a valid finalized resolution.</p></> },
  protocol: { title: "Protocol", kicker: "FaultPact", description: "The exchange in one page.", body: <><h2>Provider → Service → Pact → Coverage</h2><p>Providers bond capital behind Services. Pacts freeze measurable commitments. Customers purchase Coverage. Incidents collect evidence; GenLayer resolves facts; deterministic settlement checks the Pact.</p></> },
  contract: { title: "Contract", kicker: "Verification", description: "The frozen FaultPact V1 deployment.", body: <><h2>Studio Dev deployment</h2><div className="code-block"><code>Chain ID: 61997</code><code>Contract: 0xeb858957e3C426597245f6b59E260f1cC556Bf13</code><code>Source SHA-256: 4913a2af9cac39aac211f8f9fa66e1de8791986db495585c7a1ee9f757e7bb2e</code></div><p>The application adapts to this contract. It does not redeploy or duplicate financial logic in the API.</p></> },
  network: { title: "Network", kicker: "Runtime", description: "GenLayer Studio Development Preview.", body: <><h2>Development network context</h2><p>FaultPact currently targets Chain 61997 at <code>https://studio-dev.genlayer.com/api</code>. The product surfaces this context so users do not confuse it with a production mainnet deployment.</p></> },
  security: { title: "Security", kicker: "Protocol boundaries", description: "What the product refuses to guess.", body: <><h2>Contract wins</h2><p>The database is an index. The frontend is a read and signing surface. It does not calculate final eligibility, fabricate monitoring data, accept supplemental evidence as authoritative, or report a submitted transaction as finalized.</p><h2>Wallet boundary</h2><p>User financial actions are wallet-signed. Private keys never enter the API, database, or frontend configuration.</p></> },
  api: { title: "Integration guide", kicker: "Developers", description: "Use the API for discovery and the contract for final financial state.", body: <><h2>Read surfaces</h2><p>Public reads live under <code>/api/v1</code>. OpenAPI is available at <code>/api/docs/json</code>. Indexed rows include source and freshness context. Immutable evidence bytes are served at <code>/evidence/&lt;sha256&gt;</code>.</p><h2>Do not duplicate settlement</h2><p>Use indexed data for search and discovery, then read the contract for sensitive actionable state. Never turn an API cache into a financial authority.</p></> },
};

const nav = ["getting-started", "providers", "providers/services", "providers/pacts", "providers/capital", "customers", "customers/coverage", "customers/incidents", "customers/claims", "monitoring", "evidence", "resolution", "challenges", "protocol", "contract", "network", "security", "api"];

export function DocsLayout({ slug, children }: { slug: string; children: ReactNode }) {
  return <main className="docs-shell"><aside className="docs-sidebar"><Link className="docs-home" href="/docs">← Documentation</Link><p className="footer-label">On this page</p>{nav.map((item) => <Link className={item === slug ? "doc-nav-active" : ""} href={`/docs/${item}`} key={item}>{docs[item]?.title}</Link>)}</aside><article className="doc-article">{children}</article></main>;
}

export function DocArticle({ slug }: { slug: string }) {
  const article = docs[slug];
  if (!article) return <><p className="eyebrow">Not found</p><h1>That page is not in the protocol.</h1><p className="lede">Try the documentation index.</p><Link className="button button-dark" href="/docs">Back to docs</Link></>;
  return <><p className="eyebrow">{article.kicker}</p><h1>{article.title}</h1><p className="lede">{article.description}</p><div className="doc-rule" />{article.body}</>;
}
