"use client";

import Link from "next/link";
import { useMemo, useState } from "react";
import { asRecord, asRows, text, type JsonRecord } from "../lib/api";
import { useApi } from "../lib/use-api";
import { formatAddress, formatDate, formatGen, formatHash, formatPpm, formatPpmAsPercentage, rowValue, statusLabel } from "../lib/format";
import { Column, DataTable, DetailMeta, EmptyState, ErrorState, EvidenceBadge, Freshness, HashValue, KeyValue, LoadingState, Metric, PageHeader, Panel, ProductGlyph, StatusBadge } from "./ui";

type Resource = "providers" | "services" | "pacts" | "coverages" | "incidents" | "claims";

const listConfig: Record<Resource, { title: string; eyebrow: string; description: string; columns: Column[] }> = {
  providers: { title: "Providers", eyebrow: "Bonded operators", description: "Browse the operators putting capital behind measurable service commitments.", columns: [{ label: "Provider", key: "name", format: (value, row) => <span><b>{text(value, `Provider #${rowValue(row, "onchainId")}`)}</b><small>{formatAddress(row.address)}</small></span> }, { label: "Status", key: "status", format: (value) => <StatusBadge value={value} /> }, { label: "Capital", key: "totalCapital", format: (value) => formatGen(value) }, { label: "Services", key: "serviceCount" }] },
  services: { title: "Services", eyebrow: "What is being protected", description: "Services with indexed Pacts, monitoring signals, and incident history.", columns: [{ label: "Service", key: "name", format: (value, row) => <span><b>{text(value, `Service #${rowValue(row, "onchainId")}`)}</b><small>{text(row.serviceType, "Service")}</small></span> }, { label: "Provider", key: "providerId", format: (value) => value ? `#${text(value)}` : "—" }, { label: "Status", key: "status", format: (value) => <StatusBadge value={value} /> }, { label: "Indexed", key: "indexedAt", format: (value) => formatDate(value) }] },
  pacts: { title: "Pacts", eyebrow: "Frozen SLA terms", description: "Published reliability commitments. Read the terms before you buy Coverage.", columns: [{ label: "Pact", key: "onchainId", format: (value, row) => <span><b>Pact #{text(value)}</b><small>{text(row.regionScope, "global scope")}</small></span> }, { label: "Service", key: "serviceId", format: (value) => `Service #${text(value)}` }, { label: "Status", key: "status", format: (value) => <StatusBadge value={value} /> }, { label: "Revision", key: "revision" }] },
  coverages: { title: "Coverages", eyebrow: "Protection in force", description: "Indexed Coverage positions. Final financial state remains onchain.", columns: [{ label: "Coverage", key: "onchainId", format: (value) => <b>Coverage #{text(value)}</b> }, { label: "Buyer", key: "buyerAddress", format: (value) => formatAddress(value) }, { label: "Limit", key: "coverageLimit", format: (value) => formatGen(value) }, { label: "Status", key: "status", format: (value) => <StatusBadge value={value} /> }] },
  incidents: { title: "Incidents", eyebrow: "Canonical facts", description: "Follow evidence, resolution, challenge, and final claim evaluation without collapsing them into one verdict.", columns: [{ label: "Incident", key: "onchainId", format: (value, row) => <span><b>Incident #{text(value)}</b><small>Service #{rowValue(row, "serviceId")}</small></span> }, { label: "Status", key: "status", format: (value) => <StatusBadge value={value} /> }, { label: "Observed start", key: "observedStart", format: (value) => text(value) }, { label: "Open claims", key: "openClaims" }] },
  claims: { title: "Claims", eyebrow: "Deterministic settlement", description: "Claims are evaluated against frozen Pact terms and finalized Incident facts.", columns: [{ label: "Claim", key: "onchainId", format: (value, row) => <span><b>Claim #{text(value)}</b><small>Incident #{rowValue(row, "incidentId")}</small></span> }, { label: "Claimant", key: "claimant", format: (value) => formatAddress(value) }, { label: "Status", key: "status", format: (value) => <StatusBadge value={value} /> }, { label: "Payout", key: "payout", format: (value) => formatGen(value) }] },
};

export function ResourceList({ resource }: { resource: Resource }) {
  const config = listConfig[resource];
  const [search, setSearch] = useState("");
  const [status, setStatus] = useState("");
  const [cursor, setCursor] = useState(0);
  const [refresh, setRefresh] = useState(0);
  const state = useApi<JsonRecord[]>(`/${resource}`, { limit: 25, cursor, search: search || undefined, status: status || undefined }, refresh);
  const rows = asRows(state.data?.data);
  const pagination = state.data?.pagination;
  return <main className="content-shell"><PageHeader eyebrow={config.eyebrow} title={config.title} description={config.description} actions={<Link className="button button-dark" href="/explore">Protocol overview ↗</Link>} />
    <div className="filter-bar"><label><span>Search</span><input value={search} onChange={(event) => { setCursor(0); setSearch(event.target.value); }} placeholder={`Search ${resource}`} /></label><label><span>Status</span><select value={status} onChange={(event) => { setCursor(0); setStatus(event.target.value); }}><option value="">All statuses</option><option value="ACTIVE">Active</option><option value="PUBLISHED">Published</option><option value="OPEN">Open</option><option value="FINALIZED">Finalized</option><option value="SETTLED">Settled</option></select></label><button className="button button-quiet" onClick={() => setRefresh((value) => value + 1)}>Refresh</button></div>
    <Panel className="table-panel"><div className="table-intro"><Freshness indexedAt={state.data?.indexedAt} />{pagination ? <span className="count-label">{pagination.total} indexed</span> : null}</div>{state.loading ? <LoadingState /> : state.error ? <ErrorState message={state.error} retry={() => setRefresh((value) => value + 1)} /> : rows.length ? <DataTable rows={rows} columns={config.columns} href={(row) => `/${resource}/${rowValue(row, "onchainId", rowValue(row, "id"))}`} /> : <EmptyState title={`No ${resource} indexed`} description="The API returned no matching onchain records. This is a real protocol state, not a demo fallback." />}{pagination && !state.loading ? <div className="pagination"><button className="button button-quiet" disabled={cursor === 0} onClick={() => setCursor(Math.max(0, cursor - pagination.limit))}>← Previous</button><span>{pagination.total ? `${cursor + 1}–${Math.min(cursor + rows.length, pagination.total)} of ${pagination.total}` : "0 results"}</span><button className="button button-quiet" disabled={pagination.nextCursor === null} onClick={() => setCursor(pagination.nextCursor ?? cursor)}>Next →</button></div> : null}</Panel>
  </main>;
}

export function EntityDetail({ resource, id }: { resource: Resource; id: string }) {
  const state = useApi<JsonRecord>(`/${resource}/${id}`);
  const row = asRecord(state.data?.data);
  if (state.loading) return <main className="content-shell"><LoadingState /></main>;
  if (state.error) return <main className="content-shell"><ErrorState message={state.error} /></main>;
  return <main className="content-shell"><PageHeader eyebrow={listConfig[resource].eyebrow} title={`${listConfig[resource].title.slice(0, -1)} #${rowValue(row, "onchainId", id)}`} description="Indexed contract state. Expand raw fields only when you need the protocol shape." actions={<Link className="button button-quiet" href={`/${resource}`}>← Back to {resource}</Link>} />
    <div className="detail-grid"><Panel title="Current state" kicker="Contract-backed index"><DetailMeta row={row} /><div className="kv-grid">{Object.entries(row).filter(([key]) => !["raw", "indexedAt", "id", "deploymentId"].includes(key)).slice(0, 14).map(([key, value]) => <KeyValue key={key} label={key.replaceAll(/([A-Z])/g, " $1").replace(/^./, (letter) => letter.toUpperCase())} value={typeof value === "object" ? JSON.stringify(value) : text(value)} mono={key.toLowerCase().includes("id") || key.toLowerCase().includes("hash")} />)}</div><Freshness indexedAt={row.indexedAt} /></Panel><Panel title="Technical record" kicker="Forward-compatible raw snapshot"><details className="raw-details"><summary>View indexed JSON</summary><pre>{JSON.stringify(row.raw ?? row, null, 2)}</pre></details></Panel></div>
  </main>;
}

export function ProviderDetail({ id }: { id: string }) {
  const state = useApi<JsonRecord>(`/providers/${id}`);
  const pacts = useApi<JsonRecord[]>("/pacts", { providerId: id, limit: 10 });
  const provider = asRecord(state.data?.data);
  const vault = asRecord(provider.vault);
  const stats = asRecord(provider.stats);
  const pactRows = asRows(pacts.data?.data);
  if (state.loading) return <main className="content-shell"><LoadingState /></main>;
  if (state.error) return <main className="content-shell"><ErrorState message={state.error} /></main>;
  return <main className="content-shell"><PageHeader eyebrow="Provider profile" title={text(provider.name, `Provider #${rowValue(provider, "onchainId", id)}`)} description="Bonded capital, published commitments, and protocol statistics indexed from the frozen deployment." actions={<Link className="button button-quiet" href="/providers">← All Providers</Link>} /><div className="detail-grid"><Panel title="Capital vault" kicker="Onchain indexed state"><div className="term-grid"><Metric label="Total" value={formatGen(vault.totalCapital)} /><Metric label="Allocated" value={formatGen(vault.allocated)} /><Metric label="Reserved" value={formatGen(vault.reserved)} tone="accent" /><Metric label="Pending withdrawal" value={formatGen(vault.pending)} /></div><DetailMeta row={provider} /><Freshness indexedAt={vault.indexedAt ?? provider.indexedAt} /></Panel><Panel title="Protocol record" kicker="Provider identity"><div className="kv-grid compact"><KeyValue label="Address" value={formatAddress(provider.address)} mono /><KeyValue label="Status" value={<StatusBadge value={provider.status} />} /><KeyValue label="Published Pacts" value={text(stats.totalPacts, "—")} /><KeyValue label="Coverage sold" value={text(stats.totalCoverages, "—")} /><KeyValue label="Finalized Incidents" value={text(stats.finalizedIncidents, "—")} /><KeyValue label="Provider fault incidents" value={text(stats.providerFaultIncidents, "—")} /></div></Panel></div><Panel title="Published Pacts" kicker={`${pactRows.length} indexed records`}>{pacts.loading ? <LoadingState /> : pacts.error ? <ErrorState message={pacts.error} /> : pactRows.length ? <DataTable rows={pactRows} columns={listConfig.pacts.columns} href={(row) => `/pacts/${rowValue(row, "onchainId")}`} /> : <EmptyState title="No published Pacts indexed" description="This Provider has no matching Pact records in the current index." />}</Panel></main>;
}

export function ServiceDetail({ id }: { id: string }) {
  const state = useApi<JsonRecord>(`/services/${id}`);
  const pacts = useApi<JsonRecord[]>("/pacts", { serviceId: id, limit: 10 });
  const incidents = useApi<JsonRecord[]>("/incidents", { serviceId: id, limit: 10 });
  const monitoring = useApi<JsonRecord[]>("/monitoring");
  const service = asRecord(state.data?.data);
  const monitoringRow = asRows(monitoring.data?.data).find((row) => rowValue(row, "serviceId") === id);
  const pactRows = asRows(pacts.data?.data);
  const incidentRows = asRows(incidents.data?.data);
  if (state.loading) return <main className="content-shell"><LoadingState /></main>;
  if (state.error) return <main className="content-shell"><ErrorState message={state.error} /></main>;
  return <main className="content-shell"><PageHeader eyebrow="Service profile" title={text(service.name, `Service #${rowValue(service, "onchainId", id)}`)} description="A service is the monitored object behind one or more frozen Pacts." actions={<Link className="button button-quiet" href="/services">← All Services</Link>} /><div className="detail-grid"><Panel title="Service health" kicker={text(service.serviceType, "Service telemetry")}><div className="term-grid"><Metric label="Current status" value={<StatusBadge value={monitoringRow?.status ?? "UNKNOWN"} />} /><Metric label="Availability" value={monitoringRow?.availabilityPpm ? formatPpmAsPercentage(monitoringRow.availabilityPpm) : "UNKNOWN"} /><Metric label="P95 latency" value={monitoringRow?.p95LatencyMs ? `${text(monitoringRow.p95LatencyMs)} ms` : "UNKNOWN"} tone="accent" /><Metric label="Block lag" value={monitoringRow?.blockLagKnown ? text(monitoringRow.blockLag) : "UNKNOWN"} /></div><p className="muted">Monitoring is an operational signal. Final Incident facts and Claim results come from the contract.</p><Freshness indexedAt={monitoringRow?.indexedAt ?? service.indexedAt} source={monitoringRow ? "Indexed monitoring" : "Monitoring unavailable"} /></Panel><Panel title="Service record" kicker="Onchain indexed state"><div className="kv-grid compact"><KeyValue label="Provider" value={service.providerId ? `#${text(service.providerId)}` : "Unknown"} /><KeyValue label="Status" value={<StatusBadge value={service.status} />} /><KeyValue label="Metadata hash" value={text(service.metadataHash, "—")} mono /><KeyValue label="Scope model" value="Pact-defined" /></div><DetailMeta row={service} /></Panel></div><Panel title="Active Pacts" kicker={`${pactRows.length} indexed records`}>{pacts.loading ? <LoadingState /> : pacts.error ? <ErrorState message={pacts.error} /> : pactRows.length ? <DataTable rows={pactRows} columns={listConfig.pacts.columns} href={(row) => `/pacts/${rowValue(row, "onchainId")}`} /> : <EmptyState title="No Pacts indexed" description="This service has no Pact records in the current index." />}</Panel><Panel title="Incident history" kicker={`${incidentRows.length} indexed records`}>{incidents.loading ? <LoadingState /> : incidents.error ? <ErrorState message={incidents.error} /> : incidentRows.length ? <DataTable rows={incidentRows} columns={listConfig.incidents.columns} href={(row) => `/incidents/${rowValue(row, "onchainId")}`} /> : <EmptyState title="No Incidents indexed" description="No incident records are attached to this service." />}</Panel></main>;
}

export function CoverageDetail({ id }: { id: string }) {
  const state = useApi<JsonRecord>(`/coverages/${id}`);
  const coverage = asRecord(state.data?.data);
  const pact = asRecord(coverage.pact);
  const terms = asRecord(pact.terms);
  if (state.loading) return <main className="content-shell"><LoadingState /></main>;
  if (state.error) return <main className="content-shell"><ErrorState message={state.error} /></main>;
  return <main className="content-shell"><PageHeader eyebrow="Coverage position" title={`Coverage #${rowValue(coverage, "onchainId", id)}`} description="A Coverage records the customer’s position against a frozen Pact. Settlement remains contract-authoritative." actions={<Link className="button button-quiet" href="/coverages">← All Coverages</Link>} /><div className="detail-grid"><Panel title="Protection" kicker="Indexed contract state"><div className="term-grid"><Metric label="Status" value={<StatusBadge value={coverage.status} />} /><Metric label="Coverage limit" value={formatGen(coverage.coverageLimit)} tone="accent" /><Metric label="Provider" value={`#${rowValue(pact, "providerId")}`} /><Metric label="Pact" value={`#${rowValue(pact, "onchainId")}`} /></div><div className="kv-grid compact"><KeyValue label="Buyer" value={formatAddress(coverage.buyerAddress)} mono /><KeyValue label="Start" value={formatDate(coverage.startAt)} /><KeyValue label="End" value={formatDate(coverage.endAt)} /><KeyValue label="Claim window" value={`${rowValue(terms, "claimWindowSeconds")} seconds`} /></div><Freshness indexedAt={coverage.indexedAt} /></Panel><Panel title="Pact terms in force" kicker="Read before filing"><div className="kv-grid compact"><KeyValue label="Scope" value={rowValue(terms, "regionScope", "global")} /><KeyValue label="P95 ceiling" value={`${rowValue(terms, "p95LatencyMs")} ms`} /><KeyValue label="Min incident duration" value={`${rowValue(terms, "minIncidentDurationSeconds")} seconds`} /><KeyValue label="Max payout" value={rowValue(terms, "maxPayoutBps", "—")} mono /></div><Link className="text-link" href={`/pacts/${rowValue(pact, "onchainId")}`}>Read the full Pact →</Link></Panel></div></main>;
}

export function ClaimDetail({ id }: { id: string }) {
  const state = useApi<JsonRecord>(`/claims/${id}`);
  const claim = asRecord(state.data?.data);
  if (state.loading) return <main className="content-shell"><LoadingState /></main>;
  if (state.error) return <main className="content-shell"><ErrorState message={state.error} /></main>;
  return <main className="content-shell"><PageHeader eyebrow="Claim / settlement record" title={`Claim #${rowValue(claim, "onchainId", id)}`} description="This record is indexed from the contract. Payout and terminal status are not recomputed by the frontend." actions={<Link className="button button-quiet" href="/claims">← All Claims</Link>} /><Panel title="Settlement state" kicker="Contract-backed result"><div className="term-grid"><Metric label="Status" value={<StatusBadge value={claim.status} />} /><Metric label="Stored payout" value={formatGen(claim.payout)} tone="accent" /><Metric label="Coverage" value={`#${rowValue(claim, "coverageId")}`} /><Metric label="Incident" value={`#${rowValue(claim, "incidentId")}`} /></div><div className="kv-grid compact"><KeyValue label="Claimant" value={formatAddress(claim.claimant)} mono /><KeyValue label="Filed" value={formatDate(claim.filedAt)} /><KeyValue label="Settled" value={formatDate(claim.settledAt)} /></div><Freshness indexedAt={claim.indexedAt} /></Panel><div className="inline-links"><Link className="button button-quiet" href={`/coverages/${rowValue(claim, "coverageId")}`}>Open Coverage</Link><Link className="button button-quiet" href={`/incidents/${rowValue(claim, "incidentId")}`}>Open Incident</Link></div></main>;
}

export function PactDetail({ id }: { id: string }) {
  const state = useApi<JsonRecord>(`/pacts/${id}`);
  const capacity = useApi<JsonRecord>(`/pacts/${id}/capacity`);
  const pact = asRecord(state.data?.data);
  const terms = asRecord(pact.terms);
  const rawTerms = asRecord(asRecord(pact.raw).terms);
  const scope = rowValue(pact, "regionScope", rowValue(terms, "regionScope", rowValue(rawTerms, "region_scope", "global")));
  if (state.loading) return <main className="content-shell"><LoadingState /></main>;
  if (state.error) return <main className="content-shell"><ErrorState message={state.error} /></main>;
  return <main className="content-shell"><PageHeader eyebrow="Frozen SLA terms" title={`Pact #${rowValue(pact, "onchainId", id)}`} description="Published terms do not change in place. Coverage is evaluated against these terms and finalized Incident facts." actions={<Link className="button button-quiet" href="/pacts">← All Pacts</Link>} />
    <div className="detail-grid"><Panel title="What this Pact protects" kicker="Readable terms"><div className="term-grid"><Metric label="Availability floor" value={formatPpmAsPercentage(terms.availabilityThresholdPpm)} detail="minimum observed availability" /><Metric label="P95 latency" value={`${rowValue(terms, "p95LatencyMs")} ms`} detail="maximum observed p95" tone="accent" /><Metric label="Error rate ceiling" value={formatPpm(terms.errorRateThresholdPpm)} detail="maximum error rate" /><Metric label="Scope" value={scope} detail="normalized protocol scope" /></div><div className="kv-grid compact"><KeyValue label="Minimum incident duration" value={`${rowValue(terms, "minIncidentDurationSeconds")} seconds`} /><KeyValue label="Claim window" value={`${rowValue(terms, "claimWindowSeconds")} seconds`} /><KeyValue label="Max Coverage" value={formatGen(terms.maxCoverageAmount)} /><KeyValue label="Premium / year" value={rowValue(terms, "premiumBpsPerYear")} mono /></div></Panel><Panel title="Capacity" kicker="Current indexed state"><div className="term-grid"><Metric label="Allocated" value={formatGen(asRecord(capacity.data?.data).totalAllocated)} /><Metric label="Reserved" value={formatGen(asRecord(capacity.data?.data).totalReserved)} tone="accent" /><Metric label="Remaining" value={formatGen(asRecord(capacity.data?.data).remaining)} detail="not a guarantee until onchain purchase" /></div><Freshness indexedAt={asRecord(capacity.data?.data).indexedAt ?? capacity.data?.indexedAt} /></Panel><Panel title="How evaluation works" kicker="Protocol separation" className="explain-panel"><div className="explain-row"><ProductGlyph kind="incident" /><div><strong>Incident facts</strong><p>GenLayer resolves one canonical fact set, with evidence provenance and support IDs.</p></div></div><div className="explain-row"><ProductGlyph kind="settlement" /><div><strong>Deterministic Pact evaluation</strong><p>This Pact’s thresholds are then applied mechanically. The model does not choose the payout.</p></div></div></Panel></div>
  </main>;
}

export function IncidentDetail({ id }: { id: string }) {
  const detail = useApi<JsonRecord>(`/incidents/${id}`);
  const evidence = useApi<JsonRecord[]>(`/incidents/${id}/evidence`);
  const resolution = useApi<JsonRecord>(`/incidents/${id}/resolution`);
  const challenge = useApi<JsonRecord>(`/incidents/${id}/challenge`);
  const incident = asRecord(detail.data?.data);
  const facts = asRecord(resolution.data?.data);
  const rawFacts = asRecord(facts.raw);
  const support = asRecord(facts.supportIds ?? rawFacts.fact_support);
  const supportIds = [...new Set(Object.values(support).flatMap((value) => Array.isArray(value) ? value.map(String) : []))];
  const unusableIds = new Set((Array.isArray(rawFacts.unusable_evidence_ids) ? rawFacts.unusable_evidence_ids : Array.isArray(rawFacts.unusableEvidenceIds) ? rawFacts.unusableEvidenceIds : []).map(String));
  const evidenceRows = asRows(evidence.data?.data);
  const incidentStatus = String(incident.status ?? "OPEN").toUpperCase();
  const activeStep = incidentStatus.includes("FINAL") || incidentStatus.includes("INCONCLUSIVE") ? 4 : incidentStatus.includes("CHALLENGE") ? 3 : incidentStatus.includes("RESOL") ? 2 : incidentStatus.includes("EVID") ? 1 : 0;
  const known = (value: unknown) => value !== undefined && value !== null && value !== "";
  if (detail.loading) return <main className="content-shell"><LoadingState /></main>;
  if (detail.error) return <main className="content-shell"><ErrorState message={detail.error} /></main>;
  return <main className="content-shell"><PageHeader eyebrow="Incident / canonical facts" title={`Incident #${rowValue(incident, "onchainId", id)}`} description="Evidence, resolution, challenge, and claim evaluation are separate protocol stages." actions={<Link className="button button-quiet" href="/incidents">← All Incidents</Link>} />
    <div className="incident-hero"><div className="incident-status"><ProductGlyph kind="incident" size={36} /><div><StatusBadge value={incident.status} /><h2>Service #{rowValue(incident, "serviceId")}</h2><p>Observed {rowValue(incident, "observedStart")} → {rowValue(incident, "observedEnd")}</p></div></div><div className="incident-steps">{["OPEN", "EVIDENCE", "RESOLUTION", "CHALLENGE", "FINAL"].map((step, index) => <span className={index === activeStep ? "step-active" : index < activeStep ? "step-done" : ""} key={step}>{step}</span>)}</div></div>
    <div className="detail-grid"><Panel title="Canonical incident facts" kicker="Resolution record"><div className="fact-grid">{([["Fact status", facts.factStatus], ["Fault domain", facts.faultDomain], ["Scope", facts.scope], ["P95 latency", known(facts.p95LatencyMs) ? `${text(facts.p95LatencyMs)} ms` : "Unknown"], ["Availability", known(facts.availabilityPpm) ? formatPpmAsPercentage(facts.availabilityPpm) : "Unknown"], ["Error rate", known(facts.errorRatePpm) ? formatPpm(facts.errorRatePpm) : "Unknown"], ["Duration", known(facts.duration) ? `${text(facts.duration)} seconds` : "Derived from interval"]] as Array<[string, unknown]>).map(([label, value]) => <KeyValue key={label} label={label} value={text(value)} />)}</div><div className="support-note"><span className="status-dot" />Support IDs: {supportIds.length ? supportIds.join(", ") : "none"}</div><Freshness indexedAt={facts.indexedAt ?? resolution.data?.indexedAt} source={facts.factStatus ? "Indexed resolution" : "Resolution unavailable"} /></Panel><Panel title="Evidence ledger" kicker={`${evidenceRows.length} indexed items`}>{evidence.loading ? <LoadingState /> : evidence.error ? <ErrorState message={evidence.error} /> : evidenceRows.length ? <div className="evidence-list">{evidenceRows.map((item) => { const evidenceId = rowValue(item, "onchainId"); const excluded = unusableIds.has(evidenceId); return <div className="evidence-row" key={evidenceId}><div className="evidence-row-head"><span className="mono">Evidence #{evidenceId}</span><EvidenceBadge authoritative={item.authoritative === true} usable={item.usable === true} reporterAuthorized={item.reporterAuthorized === true} excluded={excluded} /></div><div className="evidence-details"><span>Reporter <b className="mono">{formatAddress(item.reporter)}</b></span><span>Fetch {rowValue(item, "fetchStatus")}</span><span>Hash {rowValue(item, "hashStatus")}</span><span>Schema {rowValue(item, "schemaStatus")}</span></div>{item.artifactSha256 ? <HashValue value={item.artifactSha256} /> : null}</div>; })}</div> : <EmptyState title="No evidence indexed" description="The incident has no evidence records in the API index." />}</Panel><Panel title="Challenge state" kicker="Independent review"><div className="challenge-summary"><StatusBadge value={asRecord(challenge.data?.data).status ?? "NOT_OPEN"} /><span>{asRecord(challenge.data?.data).challengeBond ? `Bond ${formatGen(asRecord(challenge.data?.data).challengeBond)}` : "No challenge record indexed"}</span></div><p className="muted">A challenge supplies authoritative provenance rules too. It does not guarantee a changed outcome.</p></Panel></div>
  </main>;
}

export function LandingStats() {
  const stats = useApi<JsonRecord>("/stats");
  const network = useApi<JsonRecord>("/network");
  const values = asRecord(stats.data?.data);
  return <div className="live-stats"><div className="live-stats-head"><span className="live-kicker"><span className="status-dot" />Live indexed protocol state</span><Freshness indexedAt={stats.data?.indexedAt} source="Contract index" /></div><div className="live-stat-grid">{([ ["Providers", values.providers], ["Services", values.services], ["Pacts", values.pacts], ["Incidents", values.incidents] ] as Array<[string, unknown]>).map(([label, value]) => <div key={label}><strong>{stats.loading ? "…" : value === undefined ? "—" : String(value)}</strong><span>{label}</span></div>)}</div>{stats.error ? <p className="live-note">Indexed state is temporarily unavailable. The protocol view is not replaced with sample data.</p> : <p className="live-note">{text(network.data?.data && asRecord(network.data.data).network, "GenLayer Studio Development Preview")} · chain {text(network.data?.data && asRecord(network.data.data).chainId, "61997")}</p>}</div>;
}

export function Dashboard({ kind }: { kind: "customer" | "provider" }) {
  const stats = useApi<JsonRecord>("/stats");
  const resource = kind === "customer" ? "coverages" : "pacts";
  const rows = useApi<JsonRecord[]>(`/${resource}`, { limit: 5 });
  const values = asRecord(stats.data?.data);
  return <main className="content-shell dashboard-shell"><PageHeader eyebrow={kind === "customer" ? "Customer workspace" : "Provider workspace"} title={kind === "customer" ? "Protection, in one place." : "Capital behind the promise."} description={kind === "customer" ? "Review indexed Coverage and follow every Incident through to a final claim result." : "See bonded, allocated, and reserved capital before you publish the next Pact."} actions={<Link className="button button-dark" href={kind === "customer" ? "/pacts" : "/provider/pacts"}>{kind === "customer" ? "Find a Pact" : "Manage Pacts"} ↗</Link>} />
    <div className="dashboard-grid"><Metric label={kind === "customer" ? "Indexed Coverages" : "Indexed Pacts"} value={String(values[kind === "customer" ? "coverages" : "pacts"] ?? "—")} /><Metric label="Open Incidents" value={String(values.incidents ?? "—")} tone="accent" /><Metric label="Indexed Claims" value={String(values.claims ?? "—")} /><Panel className="dashboard-activity" title={kind === "customer" ? "Coverage index" : "Pact index"} kicker="Indexed state"><Freshness indexedAt={rows.data?.indexedAt} />{rows.loading ? <LoadingState /> : rows.error ? <ErrorState message={rows.error} /> : asRows(rows.data?.data).length ? <DataTable rows={asRows(rows.data?.data)} columns={listConfig[resource].columns.slice(0, 4)} href={(row) => `/${resource}/${rowValue(row, "onchainId", rowValue(row, "id"))}`} /> : <EmptyState title={kind === "customer" ? "No Coverage indexed" : "No Pacts indexed"} description="Connect a wallet when you are ready to act. Browsing remains open without one." />}</Panel></div>
    <Panel title="Action readiness" kicker="Wallet-signed operations"><div className="action-grid"><div><ProductGlyph kind={kind === "customer" ? "coverage" : "bond"} /><strong>{kind === "customer" ? "Buy Coverage" : "Manage bonded capital"}</strong><p>Review first. The wallet signs user financial actions; this server never receives private keys.</p><Link href={kind === "customer" ? "/pacts" : "/provider/capital"} className="text-button">Open workflow →</Link></div><div><ProductGlyph kind="settlement" /><strong>Transaction center</strong><p>GenLayer transactions move through submission, processing, decision, and finalization. Final state is never guessed.</p><span className="muted">No current-session transactions</span></div></div></Panel>
  </main>;
}

export function MonitoringOverview() {
  const state = useApi<JsonRecord[]>("/monitoring");
  const rows = asRows(state.data?.data);
  return <main className="content-shell"><PageHeader eyebrow="Operational telemetry" title="Monitoring, without invented certainty." description="Probe data is a signal for investigation. Authoritative Incident facts still require the hardened contract evidence model." actions={<Link className="button button-dark" href="/docs/monitoring">How monitoring works ↗</Link>} />{state.loading ? <LoadingState /> : state.error ? <Panel><ErrorState message={state.error} /></Panel> : rows.length ? <div className="monitor-grid">{rows.map((row) => <Panel key={row.id as string} title={text(row.name, "Monitor target")} kicker={text(row.region, "region")}><div className="monitor-status"><StatusBadge value={row.status ?? (row.stale ? "STALE" : "UNKNOWN")} /><span>{row.lastProbeAt ? `Last probe ${formatDate(row.lastProbeAt)}` : "No probe yet"}</span></div><div className="term-grid"><Metric label="Availability" value={row.availabilityPpm ? formatPpmAsPercentage(row.availabilityPpm) : "UNKNOWN"} /><Metric label="P95 latency" value={row.p95LatencyMs ? `${text(row.p95LatencyMs)} ms` : "UNKNOWN"} tone="accent" /><Metric label="Block lag" value={row.blockLagKnown ? text(row.blockLag) : "UNKNOWN"} /></div></Panel>)}</div> : <Panel><EmptyState title="No public monitoring targets" description="Monitoring targets are managed through the protected operations API. The explorer will show real signals when the index has them." /></Panel>}</main>;
}
